export const FETCH_POPULAR = 'FETCH_POPULAR';
export const FETCH_POPULAR_COMPLETE = 'FETCH_POPULAR_COMPLETE';
export const FETCH_POPULAR_ERROR = 'FETCH_POPULAR_ERROR';

export const FETCH_RECENT = 'FETCH_RECENT';
export const FETCH_RECENT_COMPLETE = 'FETCH_RECENT_COMPLETE';
export const FETCH_RECENT_ERROR = 'FETCH_RECENT_ERROR';

export const FETCH_COMING_SOON = 'FETCH_COMING_SOON';
export const FETCH_COMING_SOON_COMPLETE = 'FETCH_COMING_SOON_COMPLETE';
export const FETCH_COMING_SOON_ERROR = 'FETCH_COMING_SOON_ERROR';
